version: '3.9'

services:
  catalog-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiapgames-catalog-api
    ports:
      - "8082:8082"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # Sobrescreve o LocalDB para apontar para o contêiner SQL Server
      ConnectionStrings__FIAPGamesConnection: "Server=sqlserver-catalog,1433;Database=fiapgames_catalog;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True"
      Jwt__Key: "ChaveSuperSecretaFiapGamesEAD12MuitoLongaParaGarantirSeguranca123!"
      Jwt__Issuer: "FiapGamesApi"
      Jwt__Audience: "FiapGamesClients"
    depends_on:
      sqlserver-catalog:
        condition: service_healthy
    networks:
      - fiapgames-network

  sqlserver-catalog:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fiapgames-catalog-db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-catalog-data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong@Passw0rd' -C -Q 'SELECT 1' || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - fiapgames-network

volumes:
  sqlserver-catalog-data:

networks:
  fiapgames-network: