apiVersion: v1
kind: Secret
metadata:
  name: catalog-service-secret
type: Opaque
stringData:
  ConnectionStrings__FIAPGamesConnection: "Server=sqlserver-catalog,1433;Database=fiapgames_catalog;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;Encrypt=False;Connect Timeout=60;ConnectRetryCount=20;ConnectRetryInterval=5"
  Jwt__Key: "ChaveSuperSecretaFiapGamesEAD12MuitoLongaParaGarantirSeguranca123!"
