// <auto-generated />
using System;
using Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _3Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogContext))]
    [Migration("20260606011448_AddCatalog")]
    partial class AddCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Biblioteca", b =>
                {
                    b.Property<int>("IdBiblioteca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBiblioteca"));

                    b.Property<int>("IdConta")
                        .HasColumnType("int");

                    b.HasKey("IdBiblioteca");

                    b.ToTable("Bibliotecas");
                });

            modelBuilder.Entity("Entities.BibliotecaJogo", b =>
                {
                    b.Property<int>("BibliotecaId")
                        .HasColumnType("int");

                    b.Property<int>("JogoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAdicao")
                        .HasColumnType("datetime2");

                    b.HasKey("BibliotecaId", "JogoId");

                    b.HasIndex("JogoId");

                    b.ToTable("BibliotecaJogos");
                });

            modelBuilder.Entity("Entities.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorTotalBruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotalLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Entities.CompraJogo", b =>
                {
                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<int>("JogoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoAplicado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CompraId", "JogoId");

                    b.ToTable("CompraJogos");
                });

            modelBuilder.Entity("Entities.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("PromocaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PromocaoId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("Entities.Promocao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaxaDesconto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Promocoes");
                });

            modelBuilder.Entity("Entities.BibliotecaJogo", b =>
                {
                    b.HasOne("Entities.Biblioteca", null)
                        .WithMany("Jogos")
                        .HasForeignKey("BibliotecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.CompraJogo", b =>
                {
                    b.HasOne("Entities.Compra", null)
                        .WithMany("CompraJogos")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Jogo", b =>
                {
                    b.HasOne("Entities.Promocao", "Promocao")
                        .WithMany()
                        .HasForeignKey("PromocaoId");

                    b.Navigation("Promocao");
                });

            modelBuilder.Entity("Entities.Biblioteca", b =>
                {
                    b.Navigation("Jogos");
                });

            modelBuilder.Entity("Entities.Compra", b =>
                {
                    b.Navigation("CompraJogos");
                });
#pragma warning restore 612, 618
        }
    }
}
